backend:
  name: github
  repo: alanbsmith/styleguide-experiment

media_folder: static/assets
public_folder: assets

collections:
  - name: guidelines
    label: Guidelines Page
    folder: guidelines
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: styles
    label: Styles Page
    folder: styles
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
